# Generated by Django 5.2.10 on 2026-01-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_time', models.DateTimeField(auto_now_add=True)),
                ('publications_count', models.IntegerField(default=0)),
                ('pages_crawled', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0)),
                ('target_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=50)),
                ('triggered_by', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=50)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Crawl Stats',
                'ordering': ['-crawl_time'],
            },
        ),
    ]
