# Generated by Django 5.2.10 on 2026-01-20 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'profile_url')},
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(blank=True, max_length=1000)),
                ('abstract', models.TextField(blank=True)),
                ('published_date', models.CharField(blank=True, max_length=100)),
                ('searchable_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='publications', to='search_engine.author')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvertedIndexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=100)),
                ('tfidf_score', models.FloatField()),
                ('term_frequency', models.IntegerField(default=1)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_entries', to='search_engine.publication')),
            ],
            options={
                'indexes': [models.Index(fields=['term'], name='search_engi_term_b443f0_idx'), models.Index(fields=['term', 'tfidf_score'], name='search_engi_term_ab725c_idx')],
                'unique_together': {('term', 'publication')},
            },
        ),
    ]
